permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: lan
  email: lank@gmail.com
  link: http://ulinka.github.io/
  weibo: http://ulinka.github.io/
  github: http://ulinka.github.io/

# 站点信息
title: lan的博客
description: lan的博客
url: http://http://ulinka.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://vignette2.wikia.nocookie.net/kyokainokanata/images/6/68/%E6%A0%97%E5%B1%B1%E6%9C%AA%E4%BE%86.png/revision/latest/scale-to-width-down/270?cb=20131227074338&path-prefix=zh
favicon: http://vignette2.wikia.nocookie.net/kyokainokanata/images/6/68/%E6%A0%97%E5%B1%B1%E6%9C%AA%E4%BE%86.png/revision/latest/scale-to-width-down/270?cb=20131227074338&path-prefix=zh

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: lan
