permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: lan
  email: lank@gmail.com
  link: http://ulinka.github.io/
  weibo: http://ulinka.github.io/
  github: http://ulinka.github.io/

# 站点信息
title: lan的博客
description: lan的博客
url: http://http://ulinka.github.io/
rss_url: /pages/rss.xml

# avatar头像及Favicon
avatar: /_posts/images/92.jpg
favicon: /_posts/images/92.jpg
# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: lan
