permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: lan
  email: lank@gmail.com
  link: http://ulinka.github.io/
  weibo: http://ulinka.github.io/
  github: http://ulinka.github.io/

# 站点信息
title: lan的博客
description: lan的博客
url: http://http://ulinka.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://img2.imgtn.bdimg.com/it/u=4071541392,4034460840&fm=21&gp=0.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: lan
